//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDSampleMVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRUDSampleMVC.Resources.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Body.
        /// </summary>
        public static string ArabicBody {
            get {
                return ResourceManager.GetString("ArabicBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Title.
        /// </summary>
        public static string ArabicTitle {
            get {
                return ResourceManager.GetString("ArabicTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Details.
        /// </summary>
        public static string CategoryDetails {
            get {
                return ResourceManager.GetString("CategoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteMSG {
            get {
                return ResourceManager.GetString("DeleteMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Category.
        /// </summary>
        public static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Body.
        /// </summary>
        public static string EnglishBody {
            get {
                return ResourceManager.GetString("EnglishBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Title.
        /// </summary>
        public static string EnglishTitle {
            get {
                return ResourceManager.GetString("EnglishTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Category.
        /// </summary>
        public static string ListCategory {
            get {
                return ResourceManager.GetString("ListCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
    }
}
